### ISSUE TITLE
Unable to reference connection strings in setup and cleanup tasks

### ISSUE THREAD

**Issue by millusdk** [Seddryck/NBi#110]
When creating setup and cleanup tasks the connectionString must be specified explicitly, it is not possible to reference the ones created in the settings section using the  @-notation.

**Comment by Seddryck** [comment]
I'll check this

**Comment by Seddryck** [comment]
Yes, indeed, I confirm the bug.

I've provided a fix at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.11.0.99042 

Could you confirm it's effectively fixing your issue? Thx.

**Comment by millusdk** [comment]
Thank you very much for your quick reply. Unfortunately it does not appear to solve the problem, here is the full error message:
NBi.NUnit.Runtime.TestSuite.Test case 6394 DS:
Exception during the setup of the test: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Hashtable parsetable, String connectionString, Boolean buildChain, Hashtable synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Hashtable synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at NBi.Core.ConnectionFactory.Get(String connectionString) in c:\projects\nbi\NBi.Core\ConnectionFactory.cs:line 18
   at NBi.Core.Batch.BatchFactory.Get(IBatchCommand command) in c:\projects\nbi\NBi.Core\Batch\BatchFactory.cs:line 17
   at NBi.Core.DecorationFactory.Get(IDecorationCommand command) in c:\projects\nbi\NBi.Core\DecorationFactory.cs:line 33
   at NBi.Core.GroupCommand.Sequential() in c:\projects\nbi\NBi.Core\GroupCommand.cs:line 58
   at NBi.Core.GroupCommand.Execute() in c:\projects\nbi\NBi.Core\GroupCommand.cs:line 26
   at NBi.NUnit.Runtime.TestSuite.ExecuteSetup(SetupXml setup) in c:\projects\nbi\NBi.NUnit.Runtime\TestSuite.cs:line 106

And here is the spedification of the setup task:
<sql-run name="6394-setup.sql" path="../NBi Test Suite /SQL/" connectionString="@Opis" />

**Comment by Seddryck** [comment]
Could you copy/paste your test and the settings? I have some troubles to reproduce.

**Comment by millusdk** [comment]
Here is the settings section, I have removed the server and instance names and the other  connection strings:
&lt;settings&gt;
    ...
    &lt;reference name="Opis"&gt;
        &lt;connectionString&gt;Data Source=;Initial Catalog=Test_OPIS;Integrated Security=true;&lt;/connectionString&gt;
    &lt;/reference&gt;
&lt;/settings&gt;

The sql task looks as follows:
&lt;sql-run name="6394-setup.sql" path="../NBi Test Suite /SQL/" connectionString="@Opis" /&gt;

**Comment by Seddryck** [comment]
Ok, now I know where to check.

**Comment by millusdk** [comment]
Sounds good. I really hope you are able to fix it :)

I don't know if it is possible, but it would also be cool if you could specify servers for etl runs the same way

-----Original Message-----

**Comment by Seddryck** [comment]
First time, I had fixed the issue for `table-reset` and `table-load` ... now it's also fixed for `sql-run` ... available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.11.0.99045

**Comment by millusdk** [comment]
Just ran my tests with the updated build and it is working :)
Thank you very much for the rapid help and fix

**Comment by Seddryck** [comment]
Ok, thx for feedback, I'll merge into the master branch and it will be part of release 1.11 (probably in a few days). 

If you want that take a look to provider a tag `etl` into the tag `reference`, create a new issue and I'll take a look when I've time.
