### ISSUE TITLE
Testing reportserver datasets throws invalid object name error

### ISSUE THREAD

**Issue by rvdpluijm** [Seddryck/NBi#155]
This might just be a simple configuration issue; I receive an error when I try to test ReportServer datasets. See the error below:

```
NBi.NUnit.Runtime.TestSuite.Initiële test Reportingserver Database:
System.Data.SqlClient.SqlException : Invalid object name 'dbo.catalog'.

at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
at System.Data.SqlClient.SqlDataReader.get_MetaData()
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
at System.Data.SqlClient.SqlCommand.ExecuteReader()
at NBi.Core.Report.DatabaseParser.SearchDataSet(String source, String reportPath, String reportName, String dataSetName, List`1& otherDataSets) in c:\projects\nbi\NBi.Core\Report\DatabaseParser.cs:line 64
at NBi.Core.Report.DatabaseParser.ExtractQuery(IQueryRequest request) in c:\projects\nbi\NBi.Core\Report\DatabaseParser.cs:line 15
at NBi.Xml.Items.ReportXml.GetQuery() in c:\projects\nbi\NBi.Xml\Items\ReportXml.cs:line 52
at NBi.NUnit.Builder.AbstractExecutionBuilder.InstantiateSystemUnderTest(ExecutionXml executionXml) in c:\projects\nbi\NBi.NUnit\Builder\AbstractExecutionBuilder.cs:line 34
at NBi.NUnit.Builder.AbstractExecutionBuilder.BaseBuild() in c:\projects\nbi\NBi.NUnit\Builder\AbstractExecutionBuilder.cs:line 26
at NBi.NUnit.Builder.AbstractTestCaseBuilder.Build() in c:\projects\nbi\NBi.NUnit\Builder\AbstractTestCaseBuilder.cs:line 52
at NBi.NUnit.TestCaseFactory.Instantiate(AbstractSystemUnderTestXml sutXml, AbstractConstraintXml ctrXml) in c:\projects\nbi\NBi.NUnit\TestCaseFactory.cs:line 140
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test) in c:\projects\nbi\NBi.NUnit.Runtime\TestSuite.cs:line 70
```

Relevant part of the code I'm using (user and passwords anonymised):

``` xml
<?xml version="1.0" encoding="utf-8"?>
<testSuite name="Unit Testing" xmlns="http://NBi/TestSuite">
    <test name="Initiële test Reportingserver Database">
        <system-under-test>
            <execution>
                <report 
                connectionString="Data Source=brytta;Database=ReportServer;User Id=########;Password=########;"
                source="Data Source=brytta;Database=HR_DWH_FIN_RAPO;User Id=########;Password=########;"
                path="/Ontwikkel/Infoview/Financieel/" 
                name="kpl_proj_hierarchie" 
                dataset="kpl_proj"/>
            </execution>
        </system-under-test>
        <assert>
            <row-count>
                <more-than or-equal="true">10</more-than>
            </row-count>
        </assert>
    </test>
</testSuite>
```

User has connect rights on both "ReportServer" and  "HR_DWH_FIN_RAPO" Databases. What am I doing wrong here?

**Comment by Seddryck** [comment]
It should work :-) ... What's your version of SQL Server Reporting Service (2008R2 ... 2016)? Could you check if the database `ReportServer` has a table `dbo.Catalog`? If yes then I think the problem is that your user has the privilege to connect to the database but not to query (read) the dbo schema.

**Comment by rvdpluijm** [comment]
We're using SSRS version 2014.
The database server has a table named dbo.Catalog, which I can without any problems query with the account I use for NBI using SQL Server 2014.

**Comment by Seddryck** [comment]
You've permuted the attributes`source`and `connectionString`. Source should be `ResportServer` and connectionString should be `HR_DWH_FIN_RAPO`

**Comment by rvdpluijm** [comment]
D'oh.. _slaps his head_. It works now, thank you! As an additional question: is it possible to provide parameters to stored procedures which are used by the report?

**Comment by FuegoArtificial** [comment]
Hi rvdplujim,

would the sample on the very bottom of the following page help you?
http://www.nbi.io/docs/query-report/
I believe if you call a dataset from the report, it doesnt matter where it comes from (stored procedure, mdx query, ...) but sets the parameter from the outside. everything else might behandled internally from the report-engine.
I'm not sure about it. It might be worth a test, though.

**Comment by rvdpluijm** [comment]
Hi FuegoArtificial,

Hm... sounds promising. I'll take a look at that!

**Comment by rvdpluijm** [comment]
Hm.. that seems to work, but it leads to another issue, which I'll post in a new one.
