### ISSUE TITLE
Object reference not set exception when testing relational table existence

### ISSUE THREAD

**Issue by DIJonA** [Seddryck/NBi#162]
Hi,

I'm trying to use NBi to build some basic table existence tests (within a relational database) but am running in to issues.  I believe I've followed the documentation [Existence of an object](http://www.nbi.io/docs/model-exists/) and [Testing the objects of the model](http://www.nbi.io/docs/model-objects/) correctly, as well as a similar closed question/issue in #108, but to no avail.

Specifically, I am trying to use the following test syntax:

```
<test name="Structure test">    
   <system-under-test>
      <structure>
         <table caption="TestTable" perspective="dbo" connectionString="Provider=SQLNCLI11;Data Source=localhost;Database=Test;Trusted_Connection=yes;"/>
      </structure>
   </system-under-test>
   <assert>
      <exists />
   </assert>
</test>
```

However, running this within NUnit throws the exception:

```
NBi.NUnit.Runtime.TestSuite.Structure test:
System.NullReferenceException : Object reference not set to an instance of an object.
```

I have tried this on a SQL 2012 instance and a SQL 2014 instance, and on two different machines, with the same result.  I've been running execution (as opposed to structural) tests on the same connection without problem.

The version of NBi I'm using is 1.12.0.7, with NUnit 2.6.4.

Am I doing something wrong here? 

Thanks,
Jon

**Comment by Seddryck** [comment]
I don't see a mistake in the test's definition. I'll check a little bit further.

**Comment by DIJonA** [comment]
Thank you.  If there's any more information I can provide you with about my environments etc then please let me know!

Jon

**Comment by Seddryck** [comment]
Could you copy/paste the whole stacktrace to help the investigation because I can't reproduce your problem.

**Comment by DIJonA** [comment]
Here it is:

```
at NBi.Core.Structure.Relational.RelationalStructureDiscoveryFactory.Instantiate(Target target, TargetType type, IEnumerable`1 filters) in c:\Program Files (x86)\TeamCity\buildAgent\work\1182887a3329b608\NBi.Core\Structure\Relational\RelationalStructureDiscoveryFactory.cs:line 25
at NBi.NUnit.Builder.AbstractStructureBuilder.InstantiateCommand(AbstractItem item) in c:\Program Files (x86)\TeamCity\buildAgent\work\1182887a3329b608\NBi.NUnit\Builder\AbstractStructureBuilder.cs:line 53
at NBi.NUnit.Builder.AbstractStructureBuilder.InstantiateSystemUnderTest(StructureXml sutXml) in c:\Program Files (x86)\TeamCity\buildAgent\work\1182887a3329b608\NBi.NUnit\Builder\AbstractStructureBuilder.cs:line 43
at NBi.NUnit.Builder.AbstractStructureBuilder.BaseBuild() in c:\Program Files (x86)\TeamCity\buildAgent\work\1182887a3329b608\NBi.NUnit\Builder\AbstractStructureBuilder.cs:line 38
at NBi.NUnit.Builder.AbstractTestCaseBuilder.Build() in c:\Program Files (x86)\TeamCity\buildAgent\work\1182887a3329b608\NBi.NUnit\Builder\AbstractTestCaseBuilder.cs:line 52
at NBi.NUnit.TestCaseFactory.Instantiate(AbstractSystemUnderTestXml sutXml, AbstractConstraintXml ctrXml) in c:\Program Files (x86)\TeamCity\buildAgent\work\1182887a3329b608\NBi.NUnit\TestCaseFactory.cs:line 142
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test) in c:\Program Files (x86)\TeamCity\buildAgent\work\1182887a3329b608\NBi.NUnit.Runtime\TestSuite.cs:line 80
```

Jon

**Comment by DIJonA** [comment]
I'm not sure if this is helpful, but I've noticed that the exception is thrown even before the connection string is evaluated: I can put a totally made-up server name in the connection string and the result is exactly the same.  Whereas if I use a made-up server name for an execution test then NUnit will hang and eventually time-out, as expected.

**Comment by Seddryck** [comment]
When testing a structure, the connectionString is parsed early to determine if it's a Relational, Multidimensional or Tabular model.

I have no access to an IDE at the moment but from GitHub and with the stacktrace, here are my findings. Your connectionString is evaluated as a "relational connectionString" (good news). Unfortunetally, at a moment I'm enforcing this connection as SqlConnection (Probably a bug) ... and your connection is not a SqlConnection but an OledbConnection ... so you've a null and a few steps later an object reference not set.

If you need a workaround, change your connection-string by removing the provider information ... it should change your connection to an SqlConnection and the test should work.

As soon as I've access to an IDE, I'll confirm this and also provide a bug fix.

**Comment by DIJonA** [comment]
Thank you, yes that workaround gets around the problem nicely!  I appreciate you looking in to this so quickly.

Regards,
Jon

**Comment by Seddryck** [comment]
Preview available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.13.0-ci.30/artifacts
