### ISSUE TITLE
Unable to change the query timeout using attribute "timeout-milliSeconds"

### ISSUE THREAD

**Issue by WimDeRons** [Seddryck/NBi#208]
When trying to use the "timeout-milliSeconds" attribute for a longer running query, the actual timeout value that is being used does not seem to be affected.

Tests have been done using values from 1000ms to 600000ms, but the CommandTimeoutException is always thrown after 30 seconds.

(Using version 1.13.0.18.)

```
Output:
NBi.NUnit.Runtime.TestSuite. <Description />:
System.AggregateException : One or more errors occurred.
  ----> NBi.Core.CommandTimeoutException : The query '<Query />' with the connection string '<ConnectionString />' wasn't finished after '30' seconds and has thrown a timeout.
  ----> System.ComponentModel.Win32Exception : The wait operation timed out

Stack trace:
at System.Threading.Tasks.Task.FastWaitAll(Task[] tasks)
at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
at NBi.NUnit.Query.EqualToConstraint.ProcessParallel(IDbCommand actual) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit\Query\EqualToConstraint.cs:line 225
at NBi.NUnit.Query.EqualToConstraint.Process(IDbCommand actual) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit\Query\EqualToConstraint.cs:line 212
at NBi.NUnit.Query.EqualToConstraint.Matches(Object actual) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit\Query\EqualToConstraint.cs:line 168
at NBi.NUnit.Runtime.TestSuite.AssertTestCase(Object systemUnderTest, Constraint constraint, String stackTrace) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit.Runtime\TestSuite.cs:line 198
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit.Runtime\TestSuite.cs:line 88
--CommandTimeoutException
at NBi.Core.Query.QuerySqlEngine.Execute(Single& elapsedSec) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core\Query\QuerySqlEngine.cs:line 184
at NBi.Core.Query.QuerySqlEngine.Execute() in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core\Query\QuerySqlEngine.cs:line 148
at NBi.Core.ResultSet.ResultSetBuilder.Build(IDbCommand cmd) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core\ResultSet\ResultSetBuilder.cs:line 55
at NBi.Core.ResultSet.ResultSetBuilder.Build(Object obj) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core\ResultSet\ResultSetBuilder.cs:line 31
at NBi.NUnit.Query.EqualToConstraint.GetResultSet(Object obj) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit\Query\EqualToConstraint.cs:line 246
at NBi.NUnit.Query.EqualToConstraint.<ProcessParallel>b__1() in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit\Query\EqualToConstraint.cs:line 230
at System.Threading.Tasks.Task.Execute()
--Win32Exception
```

**Comment by Seddryck** [comment]
@WimDeRons could you post the xml of your test? One of the key question is it the system-under-test or the eventual query in the assertion throwing the timeout?

I'll also need your connectionString (you can remove server and database name) but I need to determine the type of the connection SqlConnection, AdomdConnection or OledbConnection.

**Comment by WimDeRons** [comment]
``` javascript
<test name="Timeout test">
    <system-under-test>
        <execution>
            <query timeout-milliSeconds="200000">
                <![CDATA[
                    select  [Measures].[IP Injection MW] on 0,
                            non empty [DGO Network].[DGO Network].Children on 1
                    from    [All]
                    where   [Date and Time].[Date And Time].&[20160701000]
                ]]>
            </query>
        </execution>
    </system-under-test>
    <assert>
        <equalTo>
            <column index="0" role="key" type="text" />
            <column index="1" role="value" type="numeric" />
            <query timeout-milliSeconds="200000">
                <![CDATA[
                    SELECT  dgo.Name AS DgoNetwork, 
                            sum(f.MeteringValue) AS [IP Injection MW]
                    FROM    dbo.vwFactDGOInfeedMetering f
                    INNER   JOIN dbo.vwDimMeasureType mt ON f.PKMeasureType = mt.PKMeasureType
                    INNER   JOIN dbo.vwFactDGOInfeedMeteringAssociation a ON f.PKDate = a.PKDate AND f.PKMnemonic = a.PKMnemonic 
                    INNER   JOIN dbo.vwDimDgoNetwork dgo ON a.PKDgoNetwork = dgo.PKDgoNetwork
                    WHERE   f.PKDateTime = 20160701001
                    GROUP   BY dgo.Name
                ]]>
            </query>
        </equalTo>
    </assert>
</test>
```

**Comment by WimDeRons** [comment]
The query in the assert section is the one responsible for the timeout.
Connection string: Data Source=server;Initial Catalog=database;Integrated Security=SSPI;

**Comment by Seddryck** [comment]
Note for myself: System.Data.SqlClient namespace

**Comment by Seddryck** [comment]
I confirm that it's a bug but I've a remark, you should be sure of your query in the "assert"

**Comment by Seddryck** [comment]
Bug fix available at https://ci.appveyor.com/project/CdricLCharlier/nbi/build/1.13.0-ci.93 ... download the artefact.
