### ISSUE TITLE
I need help in setting up NBi Test environment 

### ISSUE THREAD

**Issue by gkkarthick2k** [Seddryck/NBi#247]
Hi Seddryck,

I am in the process of setting up of NBi. I wasn't able to follow the online guide. I would request you to provide video or screen shots on how to setup Nbi tool on my system and to test.

Thanks,
Karthikeyan

**Comment by Seddryck** [comment]
We can't help you if you don't describe what's wrong with your current setup, what have you tried ? What's the content of your configuration file, ... if you think that documentation is ambiguous, tell us where. Be specific and we will help you, be vague and you'll get no answer. 

Then, it will your contribution back to the community to blog/video cast or anything else about the answers that you'll get from us.

**Comment by gkkarthick2k** [comment]
Thanks for the response,

As a first step, I am trying to connect to the SQL server using query button and I have provided the following connection string, however I am unable to connect and I am getting the following error provided below,
**Connection String:**
Data Source=MAPE-WIN-SERVE\DEMO;Initial Catalog=PIP_POC_SOURCE;User ID=user_1;Password=auto@password; 

Error Message:
Source: NBi.Service
Type: System.ArgumentException
Description:
----------------------------------------
System.ArgumentException: name
   at NBi.Service.TestCaseCollectionManager.AddConnectionStrings(String name, String value) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Services\TestCaseCollectionManager.cs:line 89
   at NBi.UI.Genbi.Presenter.TestCasesPresenter.AddConnectionString(String name, String value) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.UI.Genbi\Presenter\TestCasesPresenter.cs:line 257
   at NBi.UI.Genbi.Command.TestCases.AddConnectionStringCommand.Invoke() in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.UI.Genbi\Command\TestCases\AddConnectionStringCommand.cs:line 39
   at NBi.UI.Genbi.Command.ButtonCommandBinding.OnItemClick(Object sender, EventArgs e) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.UI.Genbi\Command\ButtonCommandBinding.cs:line 49
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
[Step_1.docx](https://github.com/Seddryck/NBi/files/786720/Step_1.docx)

**Comment by Seddryck** [comment]
The title of this issue states that you're having an issue to setup a NBi environement and then you're speaking about an issue in genbi! Could you clarify this? 

If it's a UI issue, explain step by step what on which button you're clicking, how you're filling the textboxes and **why** (your goal) you're doing this!

**Comment by gkkarthick2k** [comment]
Hi Seddryck,
Let me be clear on this, I am in process of setting up the NBi tool to automate the DW/ETL validation for my project (it a pilot project for setting up of NBi)
Step 1 : I have installed the NUnit 2.5
Step 2:  Then I have created the ".config" file, ".nbits" file and ".nunit" file.
Step 3: Then I started GenBi and started creating the test suit, in the process I encountered this error.

I am sure I am missing something. Due to which I was asking about videos or screenshot documents related to installation on NBi.
Please let me know if any details required.
Mobile: *[removed by Seddryck]*

**Comment by Seddryck** [comment]
Oh I see the issue is on step 3, you should fix it.

**Comment by gkkarthick2k** [comment]
Let me know how the connection string has to be provided, please confirm if the below format is correct;
**Connection String:
Data Source=MAPE-WIN-SERVE\DEMO;Initial Catalog=PIP_POC_SOURCE;User ID=user_1;Password=auto@password;**

------------------------------------------------------------------------------------
Also let me know how to validate the flat file or excel file against Database.

**Comment by Seddryck** [comment]
Yes, it's correct

**Comment by gkkarthick2k** [comment]
How can I check if I am able to connecting to tables or NOT? or is there any way to test this?

**Comment by Seddryck** [comment]
Run a query

**Comment by gkkarthick2k** [comment]
Can u share screen shots of your NBi setup for one test case? so that I can follow the same.
Thanks

**Comment by Seddryck** [comment]
Glad that you finally solve the issue by yourself. As a general advise, I'd recommend that you carefully read the documentation to get more of NBi.

**Comment by gkkarthick2k** [comment]
Can you please share screen shots of your NBi setup for one test case? so that I can follow the same.
