### ISSUE TITLE
Unable to run ETL due to issue with dll (type missing?)

### ISSUE THREAD

**Issue by MayankJha1978** [Seddryck/NBi#273]
Getting below exception when running the test from NUnit GUI. Followed steps as per http://www.nbi.io/docs/installation-tools/

```
NBi.NUnit.Runtime.TestSuite.VerifyEtlRunTest : System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
at System.Reflection.RuntimeModule.GetTypes()
at System.Reflection.Assembly.GetTypes()
at NBi.Core.Etl.EtlRunnerFactory.Get(IEtl etl) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core\Etl\EtlRunnerFactory.cs:line 19
at NBi.Core.ExecutionFactory.Get(IExecutable executable) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core\ExecutionFactory.cs:line 14
at NBi.NUnit.Builder.AbstractExecutionNonQueryBuilder.InstantiateSystemUnderTest(ExecutionXml executionXml) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit\Builder\AbstractExecutionNonQueryBuilder.cs:line 29
at NBi.NUnit.Builder.AbstractExecutionNonQueryBuilder.BaseBuild() in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit\Builder\AbstractExecutionNonQueryBuilder.cs:line 23
at NBi.NUnit.Builder.AbstractTestCaseBuilder.Build() in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit\Builder\AbstractTestCaseBuilder.cs:line 52
at NBi.NUnit.TestCaseFactory.Instantiate(AbstractSystemUnderTestXml sutXml, AbstractConstraintXml ctrXml) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit\TestCaseFactory.cs:line 144
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit.Runtime\TestSuite.cs:line 80
```

**Comment by Seddryck** [comment]
Could you specify your test (especially the version associated to your ETL) and list all the dll named NBi.Core.SqlServer* available in your framework folder. Could you also mention the version of NBi that you're using?

**Comment by MayankJha1978** [comment]
Thanks for your response
> Framework has following dll's:

NBi.Core.SqlServer2012.dll
NBi.Core.SqlServer2014.dll
NBi.Core.SqlServer2016.dll

> ETL - SQL Version 

2012
> Downloaded following NBi version

NBi-1.14.0.7.zip


> TestProject.nbits is given below:

```
<?xml version="1.0" encoding="utf-8"?>
<testSuite name="My first test suite" xmlns="http://NBi/TestSuite">
 <test name="VerifyEtlRunTest" uid="0001">
  <system-under-test>
    <execution>
      <etl path="ETL\" name="Package_UnitTesting.dtsx">
      </etl>
    </execution>
  </system-under-test>
  <assert>
    <successful/>
  </assert>
</test>
</testSuite>

```

> TestProject.config

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
 <configSections>
  <section name="nbi" type="NBi.NUnit.Runtime.NBiSection, NBi.NUnit.Runtime"/>
 </configSections>
 <nbi testSuite="TestProject_MJ\TestProject.nbits"/>
</configuration>

```
> TestProject.nunit

```
<NUnitProject>
  <Settings activeconfig="Default" processModel="Default" domainUsage="Default" />
  <Config
    name="Default"
    binpathtype="Auto" appbase="..\"
    configfile="TestProject_MJ\TestProject.config">
    <assembly path="Framework\NBi.NUnit.Runtime.dll" />
  </Config>
</NUnitProject>
```

**Comment by Seddryck** [comment]
If you want to run a package on a SQL Server 2012, you need to add the following attribute to the ```etl``` element in your test definition: ```version="SqlServer2012"```

Keep in mind that it's not possible to remotely run an etl with NBi. Your test-suite *must* be on the same machine that your etl and the SQL Server.

**Comment by MayankJha1978** [comment]
Great! It worked but i am facing another issue which i need to sort out. Anyways thanks for help.

```
NBi.NUnit.Runtime.TestSuite.VerifyEtlRunTest:
NBi.NUnit.Runtime.CustomStackTraceAssertionException :   Expected: 
Successful execution of the etl.
 
  But was:  "Failure during execution of the etl: 
[-1073679321] - To run a SSIS package outside of SQL Server Data Tools you must install Script Task of Integration Services or higher.
"
```

**Comment by Seddryck** [comment]
I'll let this open because skipping the attribute shouldn't throw the exception you was facing. 

For the new issue, probably SSIS is not installed on the machine you're running your test suite
