### ISSUE TITLE
GenBi 1.15.0.1 Unhandled exception

### ISSUE THREAD

**Issue by janelhunt** [Seddryck/NBi#297]
Hello.  
Installed NBi with latest version of NUnit 2 framework 2.6.4.  Using GenBI version 1.15.0.1 and connecting to SQL Server 2016, I set up a connection as follows:

```Data Source=localhost;Initial Catalog=AdventureworksDW2016CTP3;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto```  and saved the connection.  

This connection works fine when running test suite in NBi with NUnit Console.

I then put a query in the query tab using the above connection in place of a csv file as follows:
```sql
SELECT
             MonthNumberOfYear
	          ,EnglishMonthName
          FROM
	          dbo.DimDate
          WHERE
	          CalendarYear >= 2014
          GROUP BY 
	            MonthNumberOfYear
             ,EnglishMonthName
          ORDER BY MonthNumberOfYear
```
I then clicked on the blue arrow button and received this message:

```
Source: System.Data
Type: System.ArgumentException
Description:
----------------------------------------
System.ArgumentException: Format of the initialization string does not conform to specification starting at index 109.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Hashtable parsetable, String connectionString, Boolean buildChain, Hashtable synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Hashtable synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at NBi.Core.ConnectionFactory.Get(String connectionString) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core\ConnectionFactory.cs:line 37
   at NBi.Core.Query.QueryEngineFactory.BuildCommand(String query, String connectionString) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core\Query\QueryEngineFactory.cs:line 140
   at NBi.Core.Query.QueryEngineFactory.GetExecutor(String query, String connectionString) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core\Query\QueryEngineFactory.cs:line 83
   at NBi.Service.TestCaseManager.ReadFromQuery(String query, String connectionString) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Services\TestCaseManager.cs:line 47
   at NBi.UI.Genbi.Presenter.TestCasesPresenter.RunQuery() in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.UI.Genbi\Presenter\TestCasesPresenter.cs:line 275
   at NBi.UI.Genbi.Command.TestCases.RunQueryCommand.Invoke() in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.UI.Genbi\Command\TestCases\RunQueryCommand.cs:line 31
   at NBi.UI.Genbi.Command.ButtonCommandBinding.OnItemClick(Object sender, EventArgs e) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.UI.Genbi\Command\ButtonCommandBinding.cs:line 49
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Kind regards
Jane

**Comment by Seddryck** [comment]
Hi Jane,

The connectionString is not valid. The token ```;auto``` at the end of the connectionString is not expected. Just remove it and everything should go well.

If it effectively fix your issue, just close the issue.

**Comment by janelhunt** [comment]
Thanks for your prompt response.
