### ISSUE TITLE
Variables not initialized depending on the runner

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#328]
The variables passed to the test can be empty, notably with the GUI of NUnit (This behaviour is really depending of the UI). When affected you'll receive the following message:

```
NBi.NUnit.Runtime.TestSuite.Use a c-sharp variable for the predicate:
NBi.Core.NBiException : The variable named 'year' is not defined.

at NBi.NUnit.Builder.AbstractTestCaseBuilder.EvaluatePotentialVariable(Object reference) in C:\Users\cedri\Projects\NBi\master\NBi.NUnit\Builder\AbstractTestCaseBuilder.cs:line 67
at NBi.NUnit.Builder.ResultSetNoRowsBuilder.InstantiateFilter() in C:\Users\cedri\Projects\NBi\master\NBi.NUnit\Builder\ResultSetNoRowsBuilder.cs:line 47
at NBi.NUnit.Builder.ResultSetAllRowsBuilder.InstantiateConstraint() in C:\Users\cedri\Projects\NBi\master\NBi.NUnit\Builder\ResultSetAllRowsBuilder.cs:line 38
at NBi.NUnit.Builder.ResultSetAllRowsBuilder.SpecificBuild() in C:\Users\cedri\Projects\NBi\master\NBi.NUnit\Builder\ResultSetAllRowsBuilder.cs:line 33
at NBi.NUnit.Builder.AbstractTestCaseBuilder.Build() in C:\Users\cedri\Projects\NBi\master\NBi.NUnit\Builder\AbstractTestCaseBuilder.cs:line 90
at NBi.NUnit.TestCaseFactory.Instantiate(AbstractSystemUnderTestXml sutXml, AbstractConstraintXml ctrXml) in C:\Users\cedri\Projects\NBi\master\NBi.NUnit\TestCaseFactory.cs:line 166
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test) in C:\Users\cedri\Projects\NBi\master\NBi.NUnit.Runtime\TestSuite.cs:line 89
```

**Comment by Seddryck** [comment]
Beta available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.17.1-beta.1+1.build.246

**Comment by Seddryck** [comment]
Packaged in v1.17.1
