### ISSUE TITLE
Can't run packages from the catalog

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#331]
The release 1.17 introduced a bug when running ETL from the catalog.

```
NBi.NUnit.Runtime.TestSuite.The package is successful:
System.TypeLoadException : GenericArguments[0], 'Microsoft.SqlServer.Management.IntegrationServices.ParameterInfo', on 'Microsoft.SqlServer.Management.Sdk.Sfc.SfcCollection`3[T,K,ParentT]' violates the constraint of type parameter 'T'.
at NBi.Core.SqlServer.IntegrationService.EtlCatalogRunner.<Parameterize>d__4.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at NBi.Core.SqlServer.IntegrationService.EtlCatalogRunner.Run() in C:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core.SqlServer\IntegrationService\EtlCatalogRunner.cs:line 52
at NBi.NUnit.Execution.SuccessfulConstraint.doMatch(IExecution actual) in C:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit\Execution\SuccessfulConstraint.cs:line 32
at NBi.NUnit.Execution.SuccessfulConstraint.Matches(Object actual) in C:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit\Execution\SuccessfulConstraint.cs:line 25
at NBi.NUnit.Runtime.TestSuite.AssertTestCase(Object systemUnderTest, Constraint constraint, String stackTrace) in C:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit.Runtime\TestSuite.cs:line 210
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test) in C:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit.Runtime\TestSuite.cs:line 96
```

Definition of ETL:

```xml
<etl
   server=".\sql2014"
   catalog="SSISDB"
   folder="Demo.NBi.Ssis"
   project="Demo.NBi.Ssis.Integration"
   name="Dimensions.dtsx"
   version="SqlServer2014"
>
   <parameter name="FlatFileScientist">C:\...\DimScientist.csv</parameter>
   <parameter name="FlatFileGeography">C:\...\DimGeography.csv</parameter>
   <parameter name="ConnectionString">Data Source=.\sql2014;Initial Catalog=Demo.NBi.Ssis;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;</parameter>
</etl>
```

**Comment by Seddryck** [comment]
Beta available at https://ci.appveyor.com/project/Seddryck/nbi/build/1.17.1-beta.1+4.build.253

**Comment by Seddryck** [comment]
Packaged in v1.17.1
