### ISSUE TITLE
Cannot run test cases with setup after reinstallation

### ISSUE THREAD

**Issue by Luidui** [Seddryck/NBi#357]
I have reinstalled the tools after upgrading my computer to Windows 10. After this, only the test cases that have no setup step pass. All my test cases that have a setup step fail with the following error message. I even get this error if the setup script is empty or does not exist.

```
Exception during the setup of the test: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at NBi.Core.Batch.BatchRunnerFactory.Get(IBatchCommand command) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core\Batch\BatchRunnerFactory.cs:line 26
   at NBi.Core.DecorationFactory.Get(IDecorationCommand command) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core\DecorationFactory.cs:line 34
   at NBi.Core.GroupCommand.Sequential() in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core\GroupCommand.cs:line 58
   at NBi.Core.GroupCommand.Execute() in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core\GroupCommand.cs:line 26
   at NBi.NUnit.Runtime.TestSuite.ExecuteSetup(SetupXml setup) in c:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.NUnit.Runtime\TestSuite.cs:line 124
```

My colleagues have no problems passing the exact same test cases on the same versions of the tools and framework on their computers.

What could be wrong with my setup?

**Comment by Seddryck** [comment]
Which version of NBi have you installed ?
Have you get the dlls named NBi.core and NBi.core.sqlserver. If yes could you list all the version (2012, 2014,2016, 2017) that you have?

**Comment by Luidui** [comment]
I have NBi.Core.dll, NBi.Core.SqlServer2012.dll, NBi.Core.SqlServer2014.dll and NBi.Core.SqlServer2016.dll (all version 1.13.0.18). I do not have NBi.Core.SqlServer2017.dll.
My colleagues who do not have the samme issue have the exact same version of NBi.

**Comment by Seddryck** [comment]
You said that in case the ```setup``` was empty, you also have this kind of issue. It's impossible to get this exact exception in case of an empty  ```setup``` ... could you paste the exact error message for this case?

About the exception that you've, you're missing some dlls. I'd guess that Microsoft.SqlServer.Smo v12.0 is not installed on your computer. If you download the latest version of NBi, you shouldn't hae this issue because I included these dlls in the setup.

**Comment by Seddryck** [comment]
I guess the problem is solved since we've no news
