### ISSUE TITLE
ConnectionString Hive ODBC Driver

### ISSUE THREAD

**Issue by steveparis242** [Seddryck/NBi#359]
Hello,

I put in place a automation test for Big Data with like database Hadoop Hive. 
My connection string is : 
DRIVER=Hortonworks Hive ODBC Driver; Host=xx.xx.xx.xxxx; Port=xxxx; HiveServerType=2; AuthMech=2; ThriftTransport=Binary;Schema=hive_database; UID=*********; PWD=*********;
When i run the test, i get the result :

>>>>
System.AggregateException : One or more errors occurred.
  ----> NBi.Core.ConnectionException : **ERROR [IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified**

Someone has already encountered this kind of problem?

Best regards,
Steve.

**Comment by Seddryck** [comment]
I doubt you have this issue with this specific connection string. Your connection string is dedicated to the HortonWorks driver but your exception is raised by the Microsoft driver. Not possible.

**Comment by steveparis242** [comment]
My résults tests :

NBi.NUnit.Runtime.TestSuite.TA.xxxxxxx:
System.AggregateException : One or more errors occurred.
  ----> NBi.Core.ConnectionException : ERROR [IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified
The connection string used was '          DRIVER=Hortonworks Hive ODBC Driver; Host=xx.xx.xx.xxxx; Port=xxxx; HiveServerType=2; AuthMech=3;ThriftTransport=Binary;          Schema=*****************; UID=*************; PWD=***********;'

at System.Threading.Tasks.Task.FastWaitAll(Task[] tasks)
at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.ProcessParallel(IResultSetService actual)
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.Process(IResultSetService actual)
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.Matches(Object actual)
at NBi.NUnit.Runtime.TestSuite.AssertTestCase(Object systemUnderTest, Constraint constraint, String stackTrace)
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test)
--ConnectionException
at NBi.Core.Query.QueryOdbcEngine.Execute(Single& elapsedSec)
at NBi.Core.Query.QueryOdbcEngine.Execute()
at NBi.Core.ResultSet.Resolver.QueryResultSetResolver.Load(IDbCommand command)
at NBi.Core.ResultSet.Resolver.QueryResultSetResolver.Execute()
at NBi.Core.ResultSet.ResultSetService.Execute()
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.<ProcessParallel>b__21_1()
at System.Threading.Tasks.Task.Execute()
