### ISSUE TITLE
any-of's reference is converted from a list of string to a single string

### ISSUE THREAD

**Issue by Seddryck** [Seddryck/NBi#365]
Apparently any-of (or within-list) is not able to read the list of possible values

The following predicate:

``` xml
<predicate operand="gender" type="text">
  <within-list>
    <item>M</item>
    <item>F</item>
  </within-list>
</predicate>
```

is systematically returning the following error: 
```
Test 'NBi.Testing.Core.Elasticsearch.Acceptance.ElasticsearchRuntimeOverrider.RunPositiveTestSuiteWithConfig("ResultSetEqualToResultSet.nbits")' failed:
	System.ArgumentNullException : Value cannot be null.
Parameter name: source
	at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
	at NBi.Core.Calculation.Predicate.Text.TextWithinList.Apply(Object x)
	at NBi.Core.Calculation.Predicate.AbstractPredicate.Execute(Object x)
	at NBi.Core.Calculation.Predicate.Combination.AndCombinationPredicateFilter.RowApply(DataRow row)
```

**Comment by Seddryck** [comment]
It was related to the Evaluation of variables ... bug fixed and available in beta at https://ci.appveyor.com/project/Seddryck/nbi/build/1.19.0-beta.5.build.386 or with 
``` ps1
Update-Package NBi.Framework -Version 1.19.0-beta0005
```
