### ISSUE TITLE
Syntax Errors in queries using ADOMD throw a timeout error after 0 seconds message

### ISSUE THREAD

**Issue by dgosbell** [Seddryck/NBi#416]
I ran a test that had a syntax error in it against an SSAS tabular model and got the following error saying that there had been a timeout:

```
1) Test Error : NBi.NUnit.Runtime.TestSuite.Compare Key Metrics 
   System.AggregateException : One or more errors occurred.
  ----> NBi.Core.CommandTimeoutException : The query '
          EVALUATE
          SUMMARIZECOLUMNS (
          FILTER('Date', 'Date'[CalendarMthKey] in {201803}),
          "Test Measure", [Test Measure],
          )
        ' with the connection string 'Provider=MSOLAP;Data Source=devserver\mssqlinst01;Initial Catalog=TabularModel;' wasn't finished after 0 second and has thrown a timeout.
   at System.Threading.Tasks.Task.FastWaitAll(Task[] tasks)
   at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
   at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.ProcessParallel(IResultSetService actual)
   at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.Process(IResultSetService actual)
   at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.Matches(Object actual)
   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at NBi.NUnit.Runtime.TestSuite.AssertTestCase(Object systemUnderTest, Constraint constraint, String stackTrace)
   at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test)
--CommandTimeoutException
   at NBi.Core.Query.Execution.DbCommandExecutionEngine.<>c.<.ctor>b__10_0(Exception ex, IDbCommand command)
   at NBi.Core.Query.Execution.AdomdExecutionEngine.HandleException(Exception ex, IDbCommand command)
   at NBi.Core.Query.Execution.DbCommandExecutionEngine.OnExecuteDataSet(IDbCommand command)
   at NBi.Core.Query.Execution.DbCommandExecutionEngine.Execute()
   at NBi.Core.ResultSet.Resolver.QueryResultSetResolver.Load(IQuery query)
   at NBi.Core.ResultSet.Resolver.QueryResultSetResolver.Execute()
   at NBi.Core.ResultSet.ResultSetService.Execute()
   at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.<>c__DisplayClass21_0.<ProcessParallel>b__0()
   at System.Threading.Tasks.Task.Execute()
```

The issue appears to be related to the following lines of code which calls the OnTimeout() method if the message **does not** start with "Timeout expired."

https://github.com/Seddryck/NBi/blob/fa1bae1c58a48064e41d5f356c10efbc48248a23/NBi.Core/Query/Execution/AdomdExecutionEngine.cs#L42-L43

I think removing the ! on line 42 might fix this issue and allow the correct exception to flow through to the test.

**Comment by Seddryck** [comment]
Thx for the report and analysis. Feel free to submit PR next time :-).

Base on your feedback , I fixed the code and a new version is available at https://ci.appveyor.com/project/Seddryck/nbi/builds/19802845 or with nuget and version ```1.19.0-beta0082```

**Comment by dgosbell** [comment]
Thanks, I will definitely submit a PR next time. I'm just starting out with NBi and was not sure 100% sure if I was on the right track so I thought I would start with an issue before lodging a PR :)
