### ISSUE TITLE
Share variables between different test-suites

### ISSUE THREAD

**Issue by phampdx** [Seddryck/NBi#473]
When <variables> is placed in top of <test-suite> it works just fine; however, if you have hundred of test suites it is hard to maintenance.  So when I moved the <variables> into .nbiset, I got error:

```
 <categories>
    <category name="Result_set" />
  </categories>
  <failure>
      <message><![CDATA[System.AggregateException : One or more errors occurred.
  ----> NBi.Core.NBiException : The variable named 'FiscalWeekNumber' is not defined. No variables are defined at the top of the test-suite.]]></message>
                                  <stack-trace><![CDATA[at System.Threading.Tasks.Task.FastWaitAll(Task[] tasks)
at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.ProcessParallel(IResultSetService actual) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.NUnit\ResultSetComparison\BaseResultSetComparisonConstraint.cs:line 154
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.Process(IResultSetService actual) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.NUnit\ResultSetComparison\BaseResultSetComparisonConstraint.cs:line 141
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.Matches(Object actual) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.NUnit\ResultSetComparison\BaseResultSetComparisonConstraint.cs:line 107
at NBi.NUnit.Runtime.TestSuite.AssertTestCase(Object systemUnderTest, Constraint constraint, String stackTrace) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.NUnit.Runtime\TestSuite.cs:line 243
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.NUnit.Runtime\TestSuite.cs:line 129
--NBiException
at NBi.Core.Scalar.Resolver.GlobalVariableScalarResolver`1.Execute() in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.Core\Scalar\Resolver\GlobalVariableScalarResolver.cs:line 48
at NBi.Core.Query.QueryParameter.GetValue() in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.Core\Query\QueryParameter.cs:line 35
at NBi.Core.Query.Command.DbCommandFactory.Instantiate(IDbConnection connection, IQuery query, ITemplateEngine engine) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.Core\Query\Command\DbCommandFactory.cs:line 45
at NBi.Core.Query.Command.DbCommandFactory.Instantiate(IClient client, IQuery query, ITemplateEngine engine) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.Core\Query\Command\DbCommandFactory.cs:line 26
at NBi.Core.Query.Command.CommandProvider.Instantiate(IClient session, IQuery query) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.Core\Query\Command\CommandProvider.cs:line 52
at NBi.Core.Query.EngineFactory`1.Instantiate(IQuery query) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.Core\Query\EngineFactory.cs:line 49
at NBi.Core.ResultSet.Resolver.QueryResultSetResolver.Load(IQuery query) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.Core\ResultSet\Resolver\QueryResultSetResolver.cs:line 44
at NBi.Core.ResultSet.Resolver.QueryResultSetResolver.Execute() in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.Core\ResultSet\Resolver\QueryResultSetResolver.cs:line 29
at NBi.Core.ResultSet.ResultSetService.Execute() in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.Core\ResultSet\ResultSetService.cs:line 26
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.<>c__DisplayClass21_0.<ProcessParallel>b__0() in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.NUnit\ResultSetComparison\BaseResultSetComparisonConstraint.cs:line 156
at System.Threading.Tasks.Task.Execute()
]]></stack-trace>
</failure>
```

Is there additional configuration to have <variables> in .nbiset  as global level?

Thanks,

Khanh

**Comment by Seddryck** [comment]
The general design guideline for NBi is to have in the test-suite itself all items that are independent of the environment (dev, test, qa ...) and in config files things that are dependent.

At the moment, I consider that variables are independent of the environment. We met a weird case where in some environnent the variable should not be evaluated but instead should take a fix value. This case is supported by [overriding a variable](http://www.nbi.io/docs/variable-override/). But we've not met the case where the formulae of the variable should be dependant of the environment. Could you explain why the formulae of ```FiscalWeekNumber``` is not the same on all your environments?

Or explain what you mean by "not easy to maintain".

**Comment by FuegoArtificial** [comment]
I have just had a similar scenario where the formula of the time is not the same among all environments.
On production the time is an expression for "yesterday". The test-environment has data until 6 months ago. I can for once test the same like the production-environment tests, but now also need to test with an expression which jumps to 6 months before.
I worked around that by adding a possibility where I can write a fixed date in one spot and a couple of SQL queries use the replace-function to replace a specific string pattern with that fixed date.
It works. A variable which could be set for an environment could be handy. Also while I generate the entire test-suites via genbi, variables defined within a testsuite are always overwritten when I use my setup.
For me, the feature could be helpful but is not important. I don't even know how to incorporate the feature in my setup properly, yet. However, I wanted to describe a scenario where the best practice might need some "bending". :)

**Comment by Seddryck** [comment]
I get the scenario, but for this case, won’t it be possible to define a variable at the top, retrieving the environment (with an override on the configuration file or with an environment variable). Then for each of the other real variables used in the test-suite having an ```if then``` or a ```switch``` based on this first variable and the selected logical path will return the formulae corresponding to the environment?

```xml
<variable name="env"/>
  <environment name="MyEnvVar"/>
</variable>
<variable name="FirstOfCurrentMonth">
  <script language="c-sharp">
    env==“test” ?
       DateTime.Now.AddMonths(-6) : 
       DateTime.Now.AddDays(1 - DateTime.Now.Day)
  </script>
</variable>
```

**Comment by Seddryck** [comment]
I fear that letting users define variables in external files will create a nightmare to debug with some variables existing in some files and not on other files.

**Comment by phampdx** [comment]
Hi @Seddryck,
Thanks for your promptly respond.  
Following is how FiscalWeekNumber parameter defined in .nbiset:

```xml
<settings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://NBi/TestSuite">
<default apply-to="everywhere">
      <connectionString>Data Source=myserver;Initial Catalog=mydb;Integrated Security=SSPI;</connectionString>
	  <parameter name="@FiscalWeekNumber" sql-type="INT">201834</parameter>
    </default>
</settings>

  <variables>
    <variable name="FiscalWeekNumberVar">
      <query-scalar connectionString="@Maindb">
        <![CDATA[ select top 1 fiscalweeknumber from dbo.DimDate WHERE FiscalWeekNumber =201834 /* debug */]]>
      </query-scalar>
    </variable>
  </variables>
```
In a .nbi files both variable reference values in .nbiset file as global:
``` xml
<test name="Validate count on a table" uid="10858">
   <system-under-test>
    <resultSet>    
     <query> <![CDATA[      
			SELECT Count(1)
				FROM dbo.DimDate AS d        
				INNER JOIN dbo.Fact1 AS f ON f.DateKey=d.DateKey        
				WHERE d.FiscalWeekNumber = @FiscalWeekNumber         
		  ]]> 
		  <parameter name="@FiscalWeekNumber">@FiscalWeekNumberVar</parameter>		  
		</query>      
     </resultSet>
	</system-under-test>
    <assert>
      <equalTo>           
		<resultSet>
          <row>
            <cell>154</cell>
          </row>
        </resultSet>	  
      </equalTo>
    </assert>
  </test>
```
With above set up, the test will be error at run time; unless, I put <variables> in the .nbi files:

```
<variables>
    <variable name="FiscalWeekNumberVar"> <query-scalar connectionString="@Maindb"> <![CDATA[ SELECT TOP 1 FiscalWeekNumber FROM dbo.DimDate WHERE FullDate < GETDATE() ORDER BY NEWID();]]> </query-scalar> </variable>
  </variables>
``` 
We have a nbi file for each dim or fact.  That's why there are many nbi files.  Plus, there are many layers of data movement btw different transformation.  I keep database connections in .nbiset file, so it is make sense to have a variable at global setting in this case can create a new nbi files with common parameter or variables.  We have about 100+ nbi files, and each have about 100+ test cases.

In additional, we use Powershell  to replace env setting in nbiset file at run time.  This way, the suite can be run on any environment.

Thanks,

Khanh

**Comment by Seddryck** [comment]
I'll take a look to a feature letting users share the same variables between different test-suites. It should also solve your use-case.

**Comment by luke-heetch** [comment]
Upvoting this feature 🚀

**Comment by lukzas** [comment]
Upvoting this feature 🚀
