### ISSUE TITLE
Could not load file or assembly 'Microsoft.SqlServer.BatchParser

### ISSUE THREAD

**Issue by phampdx** [Seddryck/NBi#474]
Following issue may relate to  [Missing DLL when using setup/sql-run](https://github.com/Seddryck/NBi/issues/396)

I tried to run SQL stmt in setup which saved in .sql file part of the test suite.  I got following error:
```
Errors and Failures:
Test Failure : NBi.NUnit.Runtime.TestSuite.TestId: 8124. Validate data
Exception during the setup of the test: Could not load file or assembly 'Microsoft.SqlServer.BatchParser, Version=14.100.0.0, Culture=neu
tral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. An attempt was made to load a program with an incorrect format.
at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandl
eOnStack type)
at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
at Microsoft.SqlServer.Management.Common.ServerConnection.GetStatements(String query, ExecutionTypes executionType, Int32& statementsToRe
verse)
at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand, ExecutionTypes executionType, Boolean retry)

at Microsoft.SqlServer.Management.Common.ServerConnection.ExecuteNonQuery(String sqlCommand)
at NBi.Core.SqlServer.Smo.BatchRunCommand.Execute() in C:\Program Files (x86)\TeamCity\buildAgent\work\abf28191c66df2d3\NBi.Core.SqlServe
r\Smo\BatchRunCommand.cs:line 35
at NBi.NUnit.Runtime.TestSuite.ExecuteSetup(SetupXml setup) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.NUnit
.Runtime\TestSuite.cs:line 169
at NBi.NUnit.Runtime.TestSuite.HandleExceptionDuringSetup(Exception ex) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7
NBi.NUnit.Runtime\TestSuite.cs:line 195
at NBi.NUnit.Runtime.TestSuite.ExecuteSetup(SetupXml setup) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.NUnit.Ru
ntime\TestSuite.cs:line 180
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test) in C:\Program Files (x86)\TeamCity\buildAgent\work\b329365f624614a7\NBi.NUnit.
Runtime\TestSuite.cs:line 115
```

My .sql file very simple:
![image](https://user-images.githubusercontent.com/6032636/56828478-40f6dc00-6816-11e9-8942-e222688c8404.png)

Following is a .nbi test file:
```xml
<test name="TestId: 8124. Validate data" uid="8124"> <setup> <sql-run connectionString="@mydb" name="my.sql" path="..\DimDataScenario\DM\" />	</setup> <system-under-test> <execution> <query> <![CDATA[ SELECT count(1) FROM dbo.DimData WHERE Deleted IS NULL AND DataKey > 0 ]]>	</query> </execution> </system-under-test> <assert> ......
```

Run with NBi version v1.19.

Thanks,

Khanh

**Comment by Seddryck** [comment]
the element ```sql-run``` is exposing an optional attribute ```version```, the default value of this attribute is ```SqlServer2014``` ... I guess you should provide this attribute with the value set to ```SqlServer2016``` [Not sure that this is still relevant].

Now if it doesn't work, you need to be sure that you've the required components installed on the machine running the test. If this machine has not the dll containing the assembly ```Microsoft.SqlServer.BatchParser``` then it won't work ... this dll has so many way to be available on a machine that it's difficult to track how exactly Microsoft expects it to be there but that could be an additional way to install it: https://www.microsoft.com/en-us/download/details.aspx?id=52676 Anyway this is not a redistribuable dll and I can't include it in my own package.

**Comment by phampdx** [comment]
I'll looking into your suggestion and reporting back.

**Comment by fluxium** [comment]
In researching this issue I came across this [issue and comment](https://github.com/Microsoft/sqltoolsservice/issues/783#issuecomment-516930530) which led me to try configuring my NBi project to target x64 rather than AnyCPU. According to the comment the BatchPaser that ships with the SMO nuget is the native binary, so in order to load it automatically your build has to target a specific architecture. All of my sql-run tasks execute without throwing errors now and I didn't have to install anything other then the SMO nuget. Here is what I did:

In Visual Studio 2019, created a new solution platform targeting x64 in Configuration Manager.
![image](https://user-images.githubusercontent.com/5983328/64209836-78296980-ce56-11e9-8d0f-ee0ccbb1287a.png)

This will create new properly groups in your csproj. Copy all properties from the previous configuration targeting AnyCPU. My x64 solution platform config looks like this:

`<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath>bin\x64\Debug\</OutputPath>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <StartAction>Program</StartAction>
    <StartProgram>$(MSBuildProjectDirectory)\..\packages\NUnit.Runners.Net4.2.6.4\tools\nunit.exe</StartProgram>
    <StartArguments>TestSuite.nunit /runselected</StartArguments>
  </PropertyGroup>`

**Comment by Seddryck** [comment]
Really interesting, thanks for sharing. Just a clarification: when you are speaking about your NBi project (the project that you are targeting to x64), you mean the project that is created when you are using NBi.VisualStudio (containing .nbits .NUnit and.config files) and not the NBi.Core project. Is it correct?

**Comment by fluxium** [comment]
Yep, correct. The project created by the NBi.VisualStudio bootstrapper.

**Comment by S1r-Lanzelot** [comment]
https://github.com/microsoft/sqltoolsservice/issues/575 - found information for the fix here.

**Comment by Seddryck** [comment]
I'll take into account for the v1.21 and check what I can do using NBi.VisualStudio to automatically change the project to x64 or x86
