### ISSUE TITLE
Problem Passing Parameters to SSAS Tabular

### ISSUE THREAD

**Issue by sqlsavant** [Seddryck/NBi#506]
I have been able to pass a parameter to a TSQL query for assertion, but I am unable to get the DAX query to work. 

Error message:  
```
-------> System.NullReferenceException : Object reference not set to an instance of an object
at System.Threading.Tasks.Task.FastWaitAll(Task[] tasks)
at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.ProcessParallel(IResultSetService actual)
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.Process(IResultSetService actual)
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.Matches(Object actual)
at NBi.NUnit.Runtime.TestSuite.AssertTestCase(Object systemUnderTest, Constraint constraint, String stackTrace)
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test)
--NullReferenceException
at NBi.Core.Scalar.Resolver.GlobalVariableScalarResolver`1.Execute()
at NBi.Core.Query.QueryParameter.GetValue()
at NBi.Core.Query.Command.DbCommandFactory.Instantiate(IDbConnection connection, IQuery query, ITemplateEngine engine)
at NBi.Core.Query.Command.DbCommandFactory.Instantiate(IClient client, IQuery query, ITemplateEngine engine)
at NBi.Core.Query.Command.CommandProvider.Instantiate(IClient session, IQuery query)
at NBi.Core.Query.EngineFactory`1.Instantiate(IQuery query)
at NBi.Core.ResultSet.Resolver.QueryResultSetResolver.Load(IQuery query)
at NBi.Core.ResultSet.Resolver.QueryResultSetResolver.Execute()
at NBi.Core.ResultSet.ResultSetService.Execute()
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.<>c__DisplayClass21_0.<ProcessParallel>b__0()
at System.Threading.Tasks.Task.Execute()
```

Connection being used:
```xml
<add name="dev-x"
         connectionString="Provider=MSOLAP.8;Data Source=XXXXX;Initial Catalog=XXX;Integrated Security=SSPI;"/>
```

Variable declaration (the variable works in the TSQL query):
```xml
<variables>
    <variable name="vTestProjectNumber">
      <query-scalar>
          SELECT TOP 1 d1.[Project Number] AS TestProjectNumber
          FROM
	          ddm.x_v m1
	          INNER JOIN ddm.y_v d1
		          ON  m1.[Key] = d1.[Key]
          WHERE m1.[Key] = (SELECT MAX(id) FROM dbo.z WHERE <blah blah>)
          GROUP BY d1.[Project Number]
          ORDER BY SUM(m1.[amount]) DESC
      </query-scalar>
    </variable>
</variables>
```

Here is the query that is failing:
```xml
 <query>
  EVALUATE
  SUMMARIZECOLUMNS (
      'Project'[Project Number],
      FILTER (
          VALUES ( 'Project'[Project Number] ),
          ( 'Project'[Project Number] = @ProjectNumber )
      ),
      "Gross Revenue Amount MTD", [Gross Revenue Amount MTD]
  )
  <parameter name="ProjectNumber">@vTestProjectNumber</parameter>
</query>
```

**Comment by Seddryck** [comment]
Thx for the report, this is most likely a bug. Could you tell me which version of NBi you're using?

According to the stacktrace, the query failing is the query evaluating the variable (the T-SQL query). The problem is not the query itself but probably that the default connection-string is not correctly forwarded to the variable during its evaluation.

To repoduce your case, I'd need a few additional info. Could you tell me :
1. what's happening if you replace the ```<query-scalar>``` by a script such as ```<script language="c-sharp">12345</script>```
2. what's happening if you add the connection-string attribute (and its value) to your tag ```<query-scalar>``` to get something such as ```<query-scalar connection-string="...">```

I just fix another issue and during the testing I had an issue similar to yours and related to the usage of ```query-scalar```. Perhaps just trying the last beta would fix your issue.

**Comment by sqlsavant** [comment]
Thanks for the quick response! 

1. I get the following error when replacing `<query-scalar>` with `<script language="c-sharp">66376</script>`. I am running a trace and do not see a query being fired against the tabular model.  I have no idea where 'N/A   ' would be coming from...it is not in my data.

```
NBi.NUnit.Runtime.TestSuite.Data: Project Dimension:
System.AggregateException : One or more errors occurred.
  ----> System.Data.OleDb.OleDbException : Conversion failed when converting the varchar value 'N/A  ' to data type int.

at System.Threading.Tasks.Task.FastWaitAll(Task[] tasks)
at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.ProcessParallel(IResultSetService actual)
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.Process(IResultSetService actual)
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.Matches(Object actual)
at NBi.NUnit.Runtime.TestSuite.AssertTestCase(Object systemUnderTest, Constraint constraint, String stackTrace)
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test)
--OleDbException
at NBi.Core.Query.Execution.OleDbExecutionEngine.HandleException(Exception ex, IDbCommand command)
at NBi.Core.Query.Execution.DbCommandExecutionEngine.OnExecuteDataSet(IDbCommand command)
at NBi.Core.Query.Execution.DbCommandExecutionEngine.Execute()
at NBi.Core.ResultSet.Resolver.QueryResultSetResolver.Load(IQuery query)
at NBi.Core.ResultSet.Resolver.QueryResultSetResolver.Execute()
at NBi.Core.ResultSet.ResultSetService.Execute()
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.<>c__DisplayClass21_0.<ProcessParallel>b__1()
at System.Threading.Tasks.Task.Execute()
```

2. I get the same error when I add the connection string 
``` xml
<query-scalar connectionString="Provider=SQLNCLI11;Data Source=xxx;Initial Catalog=xxx;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;">
```

```
> NBi.NUnit.Runtime.TestSuite.Data: Project Dimension:
System.AggregateException : One or more errors occurred.
  ----> System.NullReferenceException : Object reference not set to an instance of an object.

> at System.Threading.Tasks.Task.FastWaitAll(Task[] tasks)
at System.Threading.Tasks.Parallel.Invoke(ParallelOptions parallelOptions, Action[] actions)
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.ProcessParallel(IResultSetService actual)
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.Process(IResultSetService actual)
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.Matches(Object actual)
at NBi.NUnit.Runtime.TestSuite.AssertTestCase(Object systemUnderTest, Constraint constraint, String stackTrace)
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test)
--NullReferenceException
at NBi.Core.Scalar.Resolver.GlobalVariableScalarResolver`1.Execute()
at NBi.Core.Query.QueryParameter.GetValue()
at NBi.Core.Query.Command.DbCommandFactory.Instantiate(IDbConnection connection, IQuery query, ITemplateEngine engine)
at NBi.Core.Query.Command.DbCommandFactory.Instantiate(IClient client, IQuery query, ITemplateEngine engine)
at NBi.Core.Query.Command.CommandProvider.Instantiate(IClient session, IQuery query)
at NBi.Core.Query.EngineFactory`1.Instantiate(IQuery query)
at NBi.Core.ResultSet.Resolver.QueryResultSetResolver.Load(IQuery query)
at NBi.Core.ResultSet.Resolver.QueryResultSetResolver.Execute()
at NBi.Core.ResultSet.ResultSetService.Execute()
at NBi.NUnit.ResultSetComparison.BaseResultSetComparisonConstraint.<>c__DisplayClass21_0.<ProcessParallel>b__0()
at System.Threading.Tasks.Task.Execute()
```

**Comment by sqlsavant** [comment]
BTW...the variable and parameter works fine in my TSQL assertion query

**Comment by Seddryck** [comment]
Thx for the additional information. I'd really need to know the version of NBi that you're using.

Your two attempts give completely different results. A bit of background of how NBi is working is perhaps needed. When a query is in the assert or system-under-test and is consuming a parameter the first step is to evaluate the value to give to this parameter.  (if this parameter references a variable this evaluation is executed once and cached). Your first stacktrace clearly states that the parameter's evaluation is the issue. 

```
at NBi.Core.Scalar.Resolver.GlobalVariableScalarResolver`1.Execute()
at NBi.Core.Query.QueryParameter.GetValue()
```

It's also clear to me that it's a bug in NBi and I've the feeling that the framework doesn't handle correctly the ```variable.query-scalar``` construction.

On your first attempt (with ```variable.script```), the parameter's evaluation is successful and the framework went a few steps later. 
```
at NBi.Core.Query.Execution.DbCommandExecutionEngine.Execute()
at NBi.Core.ResultSet.Resolver.QueryResultSetResolver.Load(IQuery query)
```
During the evaluation of the DAX query ... it failed. In fact the query itself failed due to a failed conversion of 'N/A' to integer. I'm sure that if you run the same query in SSMS, you'll have the same issue. I'd say that ```'Project'[Project Number]``` is not an integer but a string and contains some values 'N/A'. Because you didn't specified the type of your parameter, NBi (especially the .Net framework) is doing its best and think that this parameter is an integer. You could change this by using the ```sql-type``` attribute when defining the attribute and specify which DAX type should be provided to the DAX query (typically the DAX type of the column ```'Project'[Project Number]```).

Your second attempt (```variable.query-scalar``` with explicit connection-string) is failing at the exact same place than your initial test (without the explicit connection-string). Due to the better result of the attempt with a ```variable.script```. I'm sure that this a bug in NBi when facing a ```variable.query-scalar```. But ... I just fixed a(nother?) bug on ```variable.query-scalar``` and I'm not able to reproduce yours. So, I'd definitively recommend that you try the last beta: https://ci.appveyor.com/api/buildjobs/72vmosh4p1qgh5ch/artifacts/NBi.NUnit.Runtime%2Fbin%2FFramework.zip or 1.21.0-beta.275 if using Nuget. to confirm that you still have a bug with this version.

Now, there are a few things that I don't understand. What do you mean *the variable and parameter works fine in my TSQL assertion query*? Are you sure that the parameter's definition is exactly the same? Could you share the whole test-suite (feel free to remove any connection-string info except provider and any intelligence in the query if you want, but I want to be sure that I correctly understand your context). If you could also share the trace of NUnit (if you're using the GUI, it's an additional tab on the right panel), it would also help to understand what's happening.

**Comment by sqlsavant** [comment]
I was using version 1.19, but I just moved to 1.20.

The way that I have this written below, the test runs and passes.  I have comments with "DOES NOT WORK" around the things that cause it to fail.  Insert code was messing up the formatting, so I've attached the file.
[TestSuite.nbits.txt](https://github.com/Seddryck/NBi/files/3534776/TestSuite.nbits.txt)

BTW, I tried to install the beta version, but nuget couldn't find it.  I'm still pretty new to this, so I may have messed up the command:  `Install-Package NBi.Framework -Version 1.21.0-beta.275`

**Comment by Seddryck** [comment]
My bad for the beta version, should be ```Install-Package NBi.Framework -Version 1.21.0-beta0275``` (or 0276 and a new version should be available in a few minutes). 

About your test, thx for the test-suite, it will be extremely helpful to reproduce. Could you confirm that your T-SQL queries use a connection-string with ```Provider=SQLNCLI``` (OleDB).

Last point, could you confirm that when you run the following query in DAX within SSMS (with the filter on project number without double-quotes for the value), you've the "N/A" issue?

```
EVALUATE
          SUMMARIZECOLUMNS (
          'Project'[Project Number],
          'Project'[Alternative Delivery Flag],
          'Project'[Billing Office Display Name],
          FILTER (
          VALUES ( 'Month'[PM Period Status Name] ),
          ( 'Month'[PM Period Status Name] = "LATEST FINAL" )
          ),
          FILTER (
          VALUES ( 'Project'[Project Number] ),
          ( 'Project'[Project Number] = 66376 )
          ),
          "Gross Revenue Amount MTD", [Gross Revenue Amount MTD]
          )
```

**Comment by sqlsavant** [comment]
Yes, SQLNCLI11.  

On the query, I have to put double-quotes around the project number. `( 'Project'[Project Number] = "66376" )`

**Comment by Seddryck** [comment]
You're facing two distinct issues: 

* The framework had a bug and was not always able to correctly understand the meaning of ```variable.query-scalar```. The bug fix is part of v1.21 and is already available in the current v1.21-beta
* A weird and complex issue about AdomdParameter and the lack of typing for them. IMO, the DAX engine considers the parameter as an integer but is facing a text when executing the FILTER clause. 

As a work-around, I'd suggest to 

* use the latest version [1.21-beta](https://ci.appveyor.com/api/buildjobs/r94j6efgy6sdflx5/artifacts/NBi.NUnit.Runtime%2Fbin%2FFramework.zip) This version includes a fix for the issue related to ```NullReferenceException```
* remove the ```sql-type``` attribute: it's not supported on ADOMD (so DAX) queries. I mentioned it in the documentation but didn't remember it: http://www.nbi.io/docs/query-parameters/#parameters-and-adomd
* force to return a string and not an integer on your evaluation of the parameter by switching to 
```SELECT TOP 1 cast(d1.[Project Number] as varchar(120)) AS TestProjectNumber ...``` ... should do the job.

I'll think again about it on how to handle this without relying on a cast/convert on the variable and create a new small-enhancement when I'll find a way to deal cleanly with this.

**Comment by sqlsavant** [comment]
I verified that the work-around works.  You are a rock star sir!  Thank you very much.

**Comment by Seddryck** [comment]
Thx for the detailed reports. I created #509 to be sure to address the root cause.
