### ISSUE TITLE
Unable to run ETL tests from docs

### ISSUE THREAD

**Issue by permind** [Seddryck/NBi#598]
Hi,
  I'm struggling to run even a basic ETL test from docs. Using fresh installation NBi.Framework (1.22).
Tests are executed on SQL Server machine.
Any hints what could be wrong here?

```xml
<test name="Basic package run" uid="0003">
  <system-under-test>
    <execution>
      <etl path="D:\ETLTests\" name="BasicLoad.dtsx" version="SqlServer2016">
      </etl>
    </execution>
  </system-under-test>
  <assert>
    <successful/>
  </assert>
</test>
```
The error:
```
NBi.NUnit.Runtime.TestSuite.Basic package run:
System.ArgumentException : Value does not fall within the expected range.
```

```xml
 <test name="Side effects with SSISDB">
  <setup>
    <etl-run
      server="localhost"
      catalog="SSISDB"
      folder="ETLTests"
      project="ETL_Tests_Demo"
      name="BasicLoad.dtsx"
      version="SqlServer2016">
    </etl-run>
  </setup>
  <system-under-test>
   <result-set>
    <query connection-string="Provider=SQLNCLI11;Server=localhost;Database=ETLTest;Trusted_Connection=yes;">
		SELECT * from dbo.srcTestTable
    </query>
   </result-set>
  </system-under-test>
  <assert>
   <equal-to>
    <query connection-string="Provider=SQLNCLI11;Server=localhost;Database=ETLTest;Trusted_Connection=yes;">
		SELECT * from dbo.dstTestTable
    </query>
   </equal-to>
  </assert>
 </test>
```
The error:
```
NBi.NUnit.Runtime.TestSuite.Side effects with SSISDB:
Exception during the setup of the test: '<>f__AnonymousType1<NBi.Core.Scalar.Resolver.IScalarResolver<string>,NBi.Core.Scalar.Resolver.IScalarResolver<string>,NBi.Core.Scalar.Resolver.IScalarResolver<string>>' does not contain a definition for 'Etl'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at ActLike_IEtlRunCommandArgs_950c1299fd5546f4ad476872d67e5969.get_Etl()
   at NBi.Core.Decoration.DataEngineering.EtlRunCommand.Execute() in C:\projects\nbi\NBi.Core\Decoration\DataEngineering\Commands\SqlServer\EtlRunCommand.cs:line 17
   at NBi.NUnit.Runtime.TestSuite.ExecuteSetup(SetupXml setup, IDictionary`2 allVariables) in C:\projects\nbi\NBi.NUnit.Runtime\TestSuite.cs:line 175
```

**Comment by Seddryck** [comment]
I probably broke something in the latetst releases of NBi related to SSIS. Since the beginning the management of the SQL Server versions has been a pain and I decided to push this to a separate package. I'll take a look to this.

**Comment by stefaniaa09** [comment]
Hi,
I have the same error in NBi.Framework 1.23.0 (NBi.VisualStudio 1.22.1). It is something broken in this release too?

Thank you!

**Comment by Seddryck** [comment]
I’m convinced that I broke something earlier and that I never fixed it.
