### ISSUE TITLE
SQL Server SSIS 2017 Support Target Date

### ISSUE THREAD

**Issue by SimZack** [Seddryck/NBi#599]
Hi All,
First of, thanks for the support of this tool! 
Do you have a target date in mind for the support of SSIS 2017 and 2019 hosted on SSIS Catalog (SQL Server)? Merci :) !
Logs when trying to exec on SQL Server 2017 SSISDB:
```
NBi.NUnit.Runtime.TestSuite.Run ETL:
System.ArgumentException : Value does not fall within the expected range.
```
```
at NBi.Core.ExecutionFactory.Instantiate(IExecutableArgs args)
at NBi.NUnit.Builder.AbstractExecutionNonQueryBuilder.InstantiateSystemUnderTest(ExecutionXml executionXml)
at NBi.NUnit.Builder.AbstractExecutionNonQueryBuilder.BaseBuild()
at NBi.NUnit.Builder.AbstractTestCaseBuilder.Build()
at NBi.NUnit.TestCaseFactory.Instantiate(AbstractSystemUnderTestXml sutXml, AbstractConstraintXml ctrXml)
at NBi.NUnit.Runtime.TestSuite.ExecuteTestCases(TestXml test, String testName, IDictionary`2 localVariables)
```
Cheers,
Simon

**Comment by Seddryck** [comment]
I probably broke something in the latest releases of NBi related to SSIS. Since the beginning, the management of the SQL Server versions has been a pain and I decided to push this to a separate package. I'll take a look at this.

**Comment by fluxium** [comment]
Hi all, 

I am curious about this too. I am getting the same results as @SimZack. I thought I would grab the trace output to see if that would help.

```
***** NBi.NUnit.Runtime.TestSuite.ETL
Loading configuration
Test loaded by NBi.NUnit.Runtime.dll
0 variables defined, 0 already evaluated.
Running test 'ETL' #
```

**Comment by Seddryck** [comment]
I'll probably work on a compatibility with SSIS Catalog during the Xmas holidays.
