### ISSUE TITLE
Error while trying to open PBIDesktop

### ISSUE THREAD

**Issue by AnimeshRoy86** [Seddryck/NBi#600]
Executing below piece of code
```xml
<tasks run-once="true" parallel="false">
        <exe-kill
          name="PBIDesktop"
          />
        <exe-run
          name="PBI File.pbix"
          path="Path to PBI File"
          />
        <connection-wait
          connection-string="PBIX = PBI File"
          timeout-milliseconds ="60000"
          />
</tasks>
```

Throwing the below error

NBi.NUnit.Runtime.TestSuite.My first test:
Exception during the setup of the test: 
```
<>f__AnonymousType2<string,NBi.Core.Scalar.Resolver.IScalarResolver<int>>' does not contain a definition for 'TimeOut'
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at ActLike_IConnectionWaitCommandArgs_ad366da17631445893e03183bbe86341.get_TimeOut()
   at NBi.Core.Decoration.DataEngineering.Commands.ConnectionWaitCommand.Execute()
   at NBi.Core.Decoration.Grouping.Commands.SequentialCommand.Execute(IEnumerable`1 listOfArgs)
   at NBi.Core.Decoration.Grouping.Commands.SequentialCommand.Execute()
   at NBi.NUnit.Runtime.TestSuite.ExecuteSetup(SetupXml setup, IDictionary`2 allVariables)
```

**Comment by Seddryck** [comment]
Fix available in `1.23.0-beta.21`
